### PR TITLE
Add missing requirements.txt to fix installation from PyPI.

### PR DESCRIPTION
**Pull request by lamby**
See also #10

### CODE REVIEW

**Comment by victor-torres** [comment]
I'll be releasing a new version tomorrow morning. Thanks.

**Comment by victor-torres** [comment]
Done

**Comment by areski** [comment]
Hi, 
I just tried to install it and go an error with missing `requirements.txt`:
      File "/tmp/pip-build-k7PVq_/python-redis-rate-limit/setup.py", line 9, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by lamby** [comment]
@victor-torres Which version was this fixed in?

@areski Which version are you attempting to install?

:)

**Comment by areski** [comment]
I'm trying to install the latest version from pypi, v0.0.4
pip install python-redis-rate-limit
Collecting python-redis-rate-limit
  Downloading python-redis-rate-limit-0.0.4.tar.gz

v0.0.4 was released on the 30-11-2017, therefore it should be up to date with the latest commits.

strangely it works if I install it directly bypassing pypi "pip install -e git+git://github.com/areski/python-redis-rate-limit.git#egg=python-redis-rate-limit"

**Comment by lamby** [comment]
``0.0.4`` on PyPI is missing the ``requirements.txt`` file from the tarball so specifying the ``git...`` directly will work. @victor-torres, perhaps you uploaded a different branch/tag something? :)

**Comment by victor-torres** [comment]
Prepended lines with `include` in the `MANIFEST.in` file and released 0.0.5, it should be working now. Thanks for reporting.

**Comment by lamby** [comment]
> Prepended lines with include in the MANIFEST.in file

Ahhh!

**Pull request merged**
