### PR TITLE
Add get_wait_time method for RateLimit

### PR DESCRIPTION
**Pull request by tlinhart**
Hi,

I propose adding a method named `get_wait_time` to the `RateLimit` class that would provide an estimate for optimal waiting time for subsequent requests sent by client. In case the limit has already been reached, this would result in a time until the limit gets reset. This would help the client in more effective requests throttling.

### CODE REVIEW

**Review by victor-torres — APPROVED** [review]
Thank you for your contribution, @tlinhart.

**Comment by victor-torres** [comment]
Could you take a look here, @italorossi?

**Comment by italorossi** [comment]
Looking..

**Comment by italorossi** [comment]
Can you write the tests so we can get this function covered?

**Comment by tlinhart** [comment]
I've added two tests for `get_wait_time` method which should test both border cases. It eventually helped to catch `TypeError` in Python 3.

@italorossi Could you please check it out?

**Comment by tlinhart** [comment]
Hi @italorossi @victor-torres ,

I just wanted to ask if this PR could eventually be merged or there's anything else I could help with.

**Comment by italorossi** [comment]
:+1:

**Pull request merged**
